version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown: 
      default-days: 7
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      nuget-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "src/IncomeTax.Presentation.Web.Node"
      - "test/IncomeTax.Presentation.Web.Functional"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      npm-deps:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
#    cooldown:
#      default-days: 7
    ignore:
      - dependency-name: "node"
        versions: [">=27"]
      - dependency-name: "mcr.microsoft.com/dotnet/sdk"
        versions: [">=11.0"]
      - dependency-name: "mcr.microsoft.com/dotnet/aspnet"
        versions: [">=11.0"]
    groups:
      docker-deps:
        patterns:
          - "*"
        
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "nginx"
        versions: [">=2"]
    groups:
      docker-compose-deps:
        patterns:
          - "*"