version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      nuget-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "src/IncomeTax.Presentation.Web.Node"
      - "test/IncomeTax.Presentation.Web.Functional"
    schedule:
      interval: "daily"
    groups:
      npm-deps:
        patterns:
          - "*"
