services:
  estimate-income-tax:
    container_name: Estimate-Income-Tax
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    expose:
      - "8080"
  
  ingress:
    container_name: Estimate-Income-Tax-Ingress
    image: caddy:2-alpine@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648
    ports:
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    restart: no
    depends_on:
      - estimate-income-tax