services:
  estimate-income-tax:
    container_name: Estimate-Income-Tax
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    expose:
      - "8080"
  
  ingress:
    container_name: Estimate-Income-Tax-Ingress
    image: caddy:2-alpine@sha256:de23def33b17fb5d1290b0f6c2add1d70780e52341896c00a4c8a2a2fe9d355e
    ports:
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    restart: no
    depends_on:
      - estimate-income-tax