events {}

http {
    upstream estimate_income_tax {
        server estimate-income-tax:8080;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        location / {
            proxy_pass http://estimate_income_tax;
        }
    }
}
