name: Functional Testing

on:
  workflow_dispatch:
  push: 
    paths:
      - 'src/IncomeTax.Presentation.Web/**'
      - 'test/IncomeTax.Presentation.Web.Functional/**'
      - '.github/workflows/functional-testing.yml'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
      
      - name: Setup Node.JS
        uses: actions/setup-node@v6
        with: 
          node-version: "lts/Krypton"
          
      - name: Run Web Application
        shell: bash
        run: docker compose up -d
        
      - name: Install Playwright
        working-directory: ./test/IncomeTax.Presentation.Web.Functional
        shell: bash
        run: |
          npm i
          npx playwright install --with-deps
          
      - name: Run Functional Testing
        working-directory: ./test/IncomeTax.Presentation.Web.Functional
        shell: bash
        run: npx playwright test --workers `nproc`