name: SonarQube

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - '!src/IncomeTax.Presentation.Web.Node/**'
      - 'test/**'
      - '!test/IncomeTax.Presentation.Web.Functional/**'
      - '.github/workflows/sonarqube.yml'
      - '.github/workflows/unit-testing.yml'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

env:
  DOTNET_VERSION: '10.x'
  JAVA_VERSION: '21'

jobs:
  build-test-analyse:
    name: Build, Test & Analyse
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          dotnet-quality: 'ga'

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install .NET Tooling
        shell: bash
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet tool install --global dotnet-coverage

      - name: Start Sonar Scanner
        shell: bash
        run: |
          dotnet-sonarscanner begin \
          /k:"zac-digital_estimate-income-tax" \
          /o:"zac-digital" \
          /d:sonar.token="${{ env.SONAR_TOKEN }}" \
          /d:sonar.exclusions=**/certs/** \
          /d:sonar.coverage.exclusions=**/certs/**,**/src/IncomeTax.Presentation.Web.Node/** \
          /d:sonar.cpd.exclusions=**playwright.config.ts \
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml \
          /d:sonar.scanner.skipJreProvisioning=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: .NET Restore
        shell: bash
        run: dotnet restore

      - name: .NET Build
        shell: bash
        run: dotnet build --no-restore --no-incremental --configuration Release

      - name: .NET Test
        shell: bash
        run: dotnet-coverage collect "dotnet test --no-build --no-restore --configuration Release" -f xml -o "coverage.xml"

      - name: Stop Sonar Scanner
        shell: bash
        run: |
          dotnet-sonarscanner end \
          /d:sonar.token="${{ env.SONAR_TOKEN }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}