name: Mutation Testing

on:
  pull_request:
    paths:
      - 'src/**'
      - '!src/IncomeTax.Presentation.Web.Node/**'
      - 'test/**'
      - '!test/IncomeTax.Presentation.Web.Functional/**'
      - '.github/workflows/stryker-mutator.yml'
      - '.github/workflows/unit-testing.yml'
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - '!src/IncomeTax.Presentation.Web.Node/**'
      - 'test/**'
      - '!test/IncomeTax.Presentation.Web.Functional/**'
      - '.github/workflows/stryker-mutator.yml'
      - '.github/workflows/unit-testing.yml'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
  
permissions: {}

jobs:
  build-and-test:
    name: Build & Mutation Test Solution
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet

      - name: Install Stryker Mutator
        shell: bash
        run: dotnet tool install --global dotnet-stryker

      - name: Run Stryker Mutator
        shell: bash
        run: dotnet stryker --configuration Release -f .github/stryker-mutator-config.json -O StrykerOutput --skip-version-check --concurrency `nproc`

      - name: Generate Markdown Report
        if: ${{ !cancelled() }}
        shell: bash
        run: |
          echo '### Stryker Mutation Report 🚀' >> $GITHUB_STEP_SUMMARY
          cat StrykerOutput/reports/mutation-report.md >> $GITHUB_STEP_SUMMARY

      - name: Upload HTML Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: 'Stryker Report'
          path: 'StrykerOutput/reports/mutation-report.html'
          compression-level: '9'